apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
spec:
  type: middleware.http.oauth2
  metadata:
    - name: clientId
      value: "<your client ID>"
    - name: clientSecret
      value: "<your client secret>"
    - name: scopes
      value: "user"
    - name: authURL
      value: "https://github.com/login/oauth/authorize"
    - name: tokenURL
      value: "https://github.com/login/oauth/access_token"
    - name: redirectURL
      value: "http://localhost:9080/v1.0/invoke/hello-dapr/method/github"
    - name: authHeaderName
      value: "x-oauth-token"
